### Домашнее задание «Библиотека numpy. Вычислительные задачи»
#### Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
import numpy as np

In [3]:
n = int(input('Введите число N: '))-1

x = np.arange(n,-1,-1)
print(x)    

Введите число N: 5
[4 3 2 1 0]


#### Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [17]:
n = int(input('Введите число N: '))-1
y = np.diag(np.arange(n,-1,-1),k=0)

print('Матрица:')
print(y)
print()
print ('Сумма значений на диагонали:', y.sum())

Введите число N: 5
Матрица:
[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]

Сумма значений на диагонали: 10


#### Задание 3

Решите систему уравнений:
   
    4x + 2y + z = 4
    x + 3y = 12
    5y + 4z = -3

In [20]:
from numpy import linalg
a = np.array([[4, 2, 1],[1, 3, 0],[0, 5, 4]])
b = np.array([4, 12, -3])

In [21]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [22]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

#### Задание 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [26]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], np.int32)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [25]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [37]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [57]:
k=0
maximum = 0
index = 0

for i in range(0, len(users_stats)):
    k =  round(cosine(users_stats[i],next_user_stats), 3)
    if k > maximum:
        maximum = k
        index = i
    
print('Самый похожий пользователь №',index, '. Косинусное сходство равно:', maximum)

Самый похожий пользователь № 7 . Косинусное сходство равно: 0.949
